### ISSUE TITLE
I searched once, cleared the field and didn't get to the home page with categories

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#232] opened 2024-04-12 16:11 UTC
When clearing the search field, we should get to the default categorized UI and not all the guides sorted alphabetically.

![2024-04-12 18 10 46 quarkus io b7e5df4d5e59](https://github.com/quarkusio/search.quarkus.io/assets/1279749/a10e0a98-2e64-420b-86bb-a23dbc034798)

**Comment by yrodiere** [comment] 2024-04-16 15:34
I reported that to @ia3andy when he sent his PR to quarkusio.github.io, but he had fixed it... I even saw it fixed myself. A regression perhaps?

**Comment by ia3andy** [comment] 2024-04-16 15:38
Let's wait to see, I think it should be ok with the latest version

**Comment by yrodiere** [comment] 2024-04-16 16:17
FWIW even trying right now, without the fix deployed, I can't reproduce your problem @gsmet :/

**Comment by ia3andy** [comment] 2024-04-18 08:27
it should be fixed

**Closed by ia3andy** 2024-04-18 08:27 UTC
